name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'

env:
  MSI_ID: '45a3f73e-5e16-4851-a91a-5c608284857b'

jobs:
  acc-tests:
    runs-on: [self-hosted, 1ES.Pool=pool-terraform-azurerm-aks]
    environment:
      name: acctests
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - uses: actions/checkout@v3
      - name: e2e test
        run: |
          az login --identity --username $MSI_ID
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          ARM_USE_MSI=true make e2e-test
      - name: version-upgrade test
        run: |
          az login --identity --username $MSI_ID
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          ARM_USE_MSI=true make version-upgrade-test
